config/routes.rb
Rails.application.routes.draw do
  resources :rol_jueces

  resources :jueces

  resources :equipos

  resources :participante_competencia

  resources :rol_tecnicos

  resources :tecnicos

  resources :jugadors

  resources :encuentros

  resources :recintos

  resources :organizadors

  get 'nueva_competencia/paso1'
  post 'nueva_competencia/paso1'

  get 'nueva_competencia/paso2'
  post 'nueva_competencia/paso2'

  get 'nueva_competencia/paso3'
  post 'nueva_competencia/paso3'

  get 'nueva_competencia/paso4'
  post 'nueva_competencia/paso4'

  get 'nueva_competencia/paso5'
  post 'nueva_competencia/paso5'

  get 'nueva_competencia/paso6'
  post 'nueva_competencia/paso6'

  get 'nueva_competencia/paso7'
  post 'nueva_competencia/paso7'

  get 'nueva_competencia/paso8'
  post 'nueva_competencia/paso8'

  get 'nueva_competencia/paso9'
  post 'nueva_competencia/paso9'

  get 'home/index'

  root :to => 'home#index'
  devise_for :users

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.administrador?
         can :manage, :all
       elsif user.organizador?
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/competencia.rb
class Competencia < ActiveRecord::Base
	
end

app/models/convocatoria.rb
class Convocatoria < ActiveRecord::Base
  belongs_to :jugador
  belongs_to :participante
end

app/models/encuentro.rb
class Encuentro < ActiveRecord::Base
end

app/models/equipo.rb
class Equipo < ActiveRecord::Base
  belongs_to :encuentro
  belongs_to :convocatoria
end

app/models/etapa.rb
class Etapa < ActiveRecord::Base
  belongs_to :competencia
  belongs_to :etapa
end

app/models/juece.rb
class Juece < ActiveRecord::Base
end

app/models/jugador.rb
class Jugador < ActiveRecord::Base
end

app/models/organizador.rb
class Organizador < ActiveRecord::Base
	has_many :Competencia
end

app/models/participante.rb
class Participante < ActiveRecord::Base
end

app/models/recinto.rb
class Recinto < ActiveRecord::Base
end

app/models/rol_cuerpo_tecnico.rb
class RolCuerpoTecnico < ActiveRecord::Base
  belongs_to :rol_tecnico
  belongs_to :participante_competencium
end

app/models/rol_juece.rb
class RolJuece < ActiveRecord::Base
end

app/models/rol_tecnico.rb
class RolTecnico < ActiveRecord::Base
end

app/models/tecnico.rb
class Tecnico < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
  ROLES = %i[administrador organizador juez entrenador jugador]
   
  def roles=(roles)
    roles = [*roles].map { |r| r.to_sym }
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end
  def has_role?(role)
    roles.include?(role)
  end
  
# in models/user.rb
  def is?(role)
    roles.include?(role.to_s)
  end
end

app/controllers/jugadors_controller.rb
class JugadorsController < ApplicationController
  before_action :set_jugador, only: [:show, :edit, :update, :destroy]

  # GET /jugadors
  # GET /jugadors.json
  def index
    @jugadors = Jugador.all
  end

  # GET /jugadors/1
  # GET /jugadors/1.json
  def show
  end

  # GET /jugadors/new
  def new
    @jugador = Jugador.new
  end

  # GET /jugadors/1/edit
  def edit
  end

  # POST /jugadors
  # POST /jugadors.json
  def create
    @jugador = Jugador.new(jugador_params)

    respond_to do |format|
      if @jugador.save
        format.html { redirect_to @jugador, notice: 'Jugador was successfully created.' }
        format.json { render :show, status: :created, location: @jugador }
      else
        format.html { render :new }
        format.json { render json: @jugador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jugadors/1
  # PATCH/PUT /jugadors/1.json
  def update
    respond_to do |format|
      if @jugador.update(jugador_params)
        format.html { redirect_to @jugador, notice: 'Jugador was successfully updated.' }
        format.json { render :show, status: :ok, location: @jugador }
      else
        format.html { render :edit }
        format.json { render json: @jugador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jugadors/1
  # DELETE /jugadors/1.json
  def destroy
    @jugador.destroy
    respond_to do |format|
      format.html { redirect_to jugadors_url, notice: 'Jugador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jugador
      @jugador = Jugador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jugador_params
      params.require(:jugador).permit(:nombre_jug, :apellido_pat_jug, :apellido_mat_jug, :rut_jug, :sexo_jug, :fecha_nac_jug, :email_jug, :foto_jug)
    end
end

app/helpers/encuentros_helper.rb
module EncuentrosHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jugadors_helper.rb
module JugadorsHelper
end

app/helpers/recintos_helper.rb
module RecintosHelper
end

app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

app/views/jugadors/_form.html.erb
<%= form_for(@jugador) do |f| %>
  <% if @jugador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jugador.errors.count, "error") %> prohibited this jugador from being saved:</h2>

      <ul>
      <% @jugador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_jug %><br>
    <%= f.text_field :nombre_jug %>
  </div>
  <div class="field">
    <%= f.label :apellido_pat_jug %><br>
    <%= f.text_field :apellido_pat_jug %>
  </div>
  <div class="field">
    <%= f.label :apellido_mat_jug %><br>
    <%= f.text_field :apellido_mat_jug %>
  </div>
  <div class="field">
    <%= f.label :rut_jug %><br>
    <%= f.text_field :rut_jug %>
  </div>
  <div class="field">
    <%= f.label :sexo_jug %><br>
    <%= f.check_box :sexo_jug %>
  </div>
  <div class="field">
    <%= f.label :fecha_nac_jug %><br>
    <%= f.date_select :fecha_nac_jug %>
  </div>
  <div class="field">
    <%= f.label :email_jug %><br>
    <%= f.text_field :email_jug %>
  </div>
  <div class="field">
    <%= f.label :foto_jug %><br>
    <%= f.text_field :foto_jug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jugadors/edit.html.erb
<h1>Editing jugador</h1>

<%= render 'form' %>

<%= link_to 'Show', @jugador %> |
<%= link_to 'Back', jugadors_path %>

app/views/jugadors/index.html.erb
<h1>Listing jugadors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre jug</th>
      <th>Apellido pat jug</th>
      <th>Apellido mat jug</th>
      <th>Rut jug</th>
      <th>Sexo jug</th>
      <th>Fecha nac jug</th>
      <th>Email jug</th>
      <th>Foto jug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jugadors.each do |jugador| %>
      <tr>
        <td><%= jugador.nombre_jug %></td>
        <td><%= jugador.apellido_pat_jug %></td>
        <td><%= jugador.apellido_mat_jug %></td>
        <td><%= jugador.rut_jug %></td>
        <td><%= jugador.sexo_jug %></td>
        <td><%= jugador.fecha_nac_jug %></td>
        <td><%= jugador.email_jug %></td>
        <td><%= jugador.foto_jug %></td>
        <td><%= link_to 'Show', jugador %></td>
        <td><%= link_to 'Edit', edit_jugador_path(jugador) %></td>
        <td><%= link_to 'Destroy', jugador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jugador', new_jugador_path %>

app/views/jugadors/new.html.erb
<h1>New jugador</h1>

<%= render 'form' %>

<%= link_to 'Back', jugadors_path %>

app/views/jugadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre jug:</strong>
  <%= @jugador.nombre_jug %>
</p>

<p>
  <strong>Apellido pat jug:</strong>
  <%= @jugador.apellido_pat_jug %>
</p>

<p>
  <strong>Apellido mat jug:</strong>
  <%= @jugador.apellido_mat_jug %>
</p>

<p>
  <strong>Rut jug:</strong>
  <%= @jugador.rut_jug %>
</p>

<p>
  <strong>Sexo jug:</strong>
  <%= @jugador.sexo_jug %>
</p>

<p>
  <strong>Fecha nac jug:</strong>
  <%= @jugador.fecha_nac_jug %>
</p>

<p>
  <strong>Email jug:</strong>
  <%= @jugador.email_jug %>
</p>

<p>
  <strong>Foto jug:</strong>
  <%= @jugador.foto_jug %>
</p>

<%= link_to 'Edit', edit_jugador_path(@jugador) %> |
<%= link_to 'Back', jugadors_path %>