config/routes.rb
Rails.application.routes.draw do
  resources :rol_jueces

  resources :jueces

  resources :equipos

  resources :participante_competencia

  resources :rol_tecnicos

  resources :tecnicos

  resources :jugadors

  resources :encuentros

  resources :recintos

  resources :organizadors

  get 'nueva_competencia/paso1'
  post 'nueva_competencia/paso1'

  get 'nueva_competencia/paso2'
  post 'nueva_competencia/paso2'

  get 'nueva_competencia/paso3'
  post 'nueva_competencia/paso3'

  get 'nueva_competencia/paso4'
  post 'nueva_competencia/paso4'

  get 'nueva_competencia/paso5'
  post 'nueva_competencia/paso5'

  get 'nueva_competencia/paso6'
  post 'nueva_competencia/paso6'

  get 'nueva_competencia/paso7'
  post 'nueva_competencia/paso7'

  get 'nueva_competencia/paso8'
  post 'nueva_competencia/paso8'

  get 'nueva_competencia/paso9'
  post 'nueva_competencia/paso9'

  get 'home/index'

  root :to => 'home#index'
  devise_for :users

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.administrador?
         can :manage, :all
       elsif user.organizador?
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/competencia.rb
class Competencia < ActiveRecord::Base
	
end

app/models/convocatoria.rb
class Convocatoria < ActiveRecord::Base
  belongs_to :jugador
  belongs_to :participante
end

app/models/encuentro.rb
class Encuentro < ActiveRecord::Base
end

app/models/equipo.rb
class Equipo < ActiveRecord::Base
  belongs_to :encuentro
  belongs_to :convocatoria
end

app/models/etapa.rb
class Etapa < ActiveRecord::Base
  belongs_to :competencia
  belongs_to :etapa
end

app/models/juece.rb
class Juece < ActiveRecord::Base
end

app/models/jugador.rb
class Jugador < ActiveRecord::Base
end

app/models/organizador.rb
class Organizador < ActiveRecord::Base
	has_many :Competencia
end

app/models/participante.rb
class Participante < ActiveRecord::Base
end

app/models/recinto.rb
class Recinto < ActiveRecord::Base
end

app/models/rol_juece.rb
class RolJuece < ActiveRecord::Base
end

app/models/rol_tecnico.rb
class RolTecnico < ActiveRecord::Base
end

app/models/tecnico.rb
class Tecnico < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
  ROLES = %i[administrador organizador juez entrenador jugador]
   
  def roles=(roles)
    roles = [*roles].map { |r| r.to_sym }
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end
  def has_role?(role)
    roles.include?(role)
  end
  
# in models/user.rb
  def is?(role)
    roles.include?(role.to_s)
  end
end

app/controllers/rol_jueces_controller.rb
class RolJuecesController < ApplicationController
  before_action :set_rol_juece, only: [:show, :edit, :update, :destroy]

  # GET /rol_jueces
  # GET /rol_jueces.json
  def index
    @rol_jueces = RolJuece.all
  end

  # GET /rol_jueces/1
  # GET /rol_jueces/1.json
  def show
  end

  # GET /rol_jueces/new
  def new
    @rol_juece = RolJuece.new
  end

  # GET /rol_jueces/1/edit
  def edit
  end

  # POST /rol_jueces
  # POST /rol_jueces.json
  def create
    @rol_juece = RolJuece.new(rol_juece_params)

    respond_to do |format|
      if @rol_juece.save
        format.html { redirect_to @rol_juece, notice: 'Rol juece was successfully created.' }
        format.json { render :show, status: :created, location: @rol_juece }
      else
        format.html { render :new }
        format.json { render json: @rol_juece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rol_jueces/1
  # PATCH/PUT /rol_jueces/1.json
  def update
    respond_to do |format|
      if @rol_juece.update(rol_juece_params)
        format.html { redirect_to @rol_juece, notice: 'Rol juece was successfully updated.' }
        format.json { render :show, status: :ok, location: @rol_juece }
      else
        format.html { render :edit }
        format.json { render json: @rol_juece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rol_jueces/1
  # DELETE /rol_jueces/1.json
  def destroy
    @rol_juece.destroy
    respond_to do |format|
      format.html { redirect_to rol_jueces_url, notice: 'Rol juece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol_juece
      @rol_juece = RolJuece.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_juece_params
      params.require(:rol_juece).permit(:tipo_rol_juez)
    end
end

app/helpers/encuentros_helper.rb
module EncuentrosHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jugadors_helper.rb
module JugadorsHelper
end

app/helpers/recintos_helper.rb
module RecintosHelper
end

app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

app/views/rol_jueces/_form.html.erb
<%= form_for(@rol_juece) do |f| %>
  <% if @rol_juece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rol_juece.errors.count, "error") %> prohibited this rol_juece from being saved:</h2>

      <ul>
      <% @rol_juece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_rol_juez %><br>
    <%= f.text_field :tipo_rol_juez %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rol_jueces/edit.html.erb
<h1>Editing rol_juece</h1>

<%= render 'form' %>

<%= link_to 'Show', @rol_juece %> |
<%= link_to 'Back', rol_jueces_path %>

app/views/rol_jueces/index.html.erb
<h1>Listing rol_jueces</h1>

<table>
  <thead>
    <tr>
      <th>Tipo rol juez</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rol_jueces.each do |rol_juece| %>
      <tr>
        <td><%= rol_juece.tipo_rol_juez %></td>
        <td><%= link_to 'Show', rol_juece %></td>
        <td><%= link_to 'Edit', edit_rol_juece_path(rol_juece) %></td>
        <td><%= link_to 'Destroy', rol_juece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rol juece', new_rol_juece_path %>

app/views/rol_jueces/new.html.erb
<h1>New rol_juece</h1>

<%= render 'form' %>

<%= link_to 'Back', rol_jueces_path %>

app/views/rol_jueces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo rol juez:</strong>
  <%= @rol_juece.tipo_rol_juez %>
</p>

<%= link_to 'Edit', edit_rol_juece_path(@rol_juece) %> |
<%= link_to 'Back', rol_jueces_path %>