config/routes.rb
Rails.application.routes.draw do
  resources :rol_jueces

  resources :jueces

  resources :equipos

  resources :participante_competencia

  resources :rol_tecnicos

  resources :tecnicos

  resources :jugadors

  resources :encuentros

  resources :recintos

  resources :organizadors

  get 'nueva_competencia/paso1'
  post 'nueva_competencia/paso1'

  get 'nueva_competencia/paso2'
  post 'nueva_competencia/paso2'

  get 'nueva_competencia/paso3'
  post 'nueva_competencia/paso3'

  get 'nueva_competencia/paso4'
  post 'nueva_competencia/paso4'

  get 'nueva_competencia/paso5'
  post 'nueva_competencia/paso5'

  get 'nueva_competencia/paso6'
  post 'nueva_competencia/paso6'

  get 'nueva_competencia/paso7'
  post 'nueva_competencia/paso7'

  get 'nueva_competencia/paso8'
  post 'nueva_competencia/paso8'

  get 'nueva_competencia/paso9'
  post 'nueva_competencia/paso9'

  get 'home/index'

  root :to => 'home#index'
  devise_for :users

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.administrador?
         can :manage, :all
       elsif user.organizador?
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/competencia.rb
class Competencia < ActiveRecord::Base
	
end

app/models/convocatoria.rb
class Convocatoria < ActiveRecord::Base
  belongs_to :jugador
  belongs_to :participante
end

app/models/encuentro.rb
class Encuentro < ActiveRecord::Base
end

app/models/equipo.rb
class Equipo < ActiveRecord::Base
  belongs_to :encuentro
  belongs_to :convocatoria
end

app/models/etapa.rb
class Etapa < ActiveRecord::Base
  belongs_to :competencia
  belongs_to :etapa
end

app/models/juece.rb
class Juece < ActiveRecord::Base
end

app/models/jugador.rb
class Jugador < ActiveRecord::Base
end

app/models/organizador.rb
class Organizador < ActiveRecord::Base
	has_many :Competencia
end

app/models/participante.rb
class Participante < ActiveRecord::Base
end

app/models/recinto.rb
class Recinto < ActiveRecord::Base
end

app/models/rol_juece.rb
class RolJuece < ActiveRecord::Base
end

app/models/rol_tecnico.rb
class RolTecnico < ActiveRecord::Base
end

app/models/tecnico.rb
class Tecnico < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
  ROLES = %i[administrador organizador juez entrenador jugador]
   
  def roles=(roles)
    roles = [*roles].map { |r| r.to_sym }
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end
  def has_role?(role)
    roles.include?(role)
  end
  
# in models/user.rb
  def is?(role)
    roles.include?(role.to_s)
  end
end

app/controllers/jueces_controller.rb
class JuecesController < ApplicationController
  before_action :set_juece, only: [:show, :edit, :update, :destroy]

  # GET /jueces
  # GET /jueces.json
  def index
    @jueces = Juece.all
  end

  # GET /jueces/1
  # GET /jueces/1.json
  def show
  end

  # GET /jueces/new
  def new
    @juece = Juece.new
  end

  # GET /jueces/1/edit
  def edit
  end

  # POST /jueces
  # POST /jueces.json
  def create
    @juece = Juece.new(juece_params)

    respond_to do |format|
      if @juece.save
        format.html { redirect_to @juece, notice: 'Juece was successfully created.' }
        format.json { render :show, status: :created, location: @juece }
      else
        format.html { render :new }
        format.json { render json: @juece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jueces/1
  # PATCH/PUT /jueces/1.json
  def update
    respond_to do |format|
      if @juece.update(juece_params)
        format.html { redirect_to @juece, notice: 'Juece was successfully updated.' }
        format.json { render :show, status: :ok, location: @juece }
      else
        format.html { render :edit }
        format.json { render json: @juece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jueces/1
  # DELETE /jueces/1.json
  def destroy
    @juece.destroy
    respond_to do |format|
      format.html { redirect_to jueces_url, notice: 'Juece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_juece
      @juece = Juece.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def juece_params
      params.require(:juece).permit(:nombre_juez, :apellido_pat_juez, :apellido_mat_juez, :rut_juez, :sexo_juez, :fecha_nac_juez, :email_juez, :foto_juez)
    end
end

app/helpers/encuentros_helper.rb
module EncuentrosHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jugadors_helper.rb
module JugadorsHelper
end

app/helpers/recintos_helper.rb
module RecintosHelper
end

app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

app/views/jueces/_form.html.erb
<%= form_for(@juece) do |f| %>
  <% if @juece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@juece.errors.count, "error") %> prohibited this juece from being saved:</h2>

      <ul>
      <% @juece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_juez %><br>
    <%= f.text_field :nombre_juez %>
  </div>
  <div class="field">
    <%= f.label :apellido_pat_juez %><br>
    <%= f.text_field :apellido_pat_juez %>
  </div>
  <div class="field">
    <%= f.label :apellido_mat_juez %><br>
    <%= f.text_field :apellido_mat_juez %>
  </div>
  <div class="field">
    <%= f.label :rut_juez %><br>
    <%= f.text_field :rut_juez %>
  </div>
  <div class="field">
    <%= f.label :sexo_juez %><br>
    <%= f.check_box :sexo_juez %>
  </div>
  <div class="field">
    <%= f.label :fecha_nac_juez %><br>
    <%= f.date_select :fecha_nac_juez %>
  </div>
  <div class="field">
    <%= f.label :email_juez %><br>
    <%= f.text_field :email_juez %>
  </div>
  <div class="field">
    <%= f.label :foto_juez %><br>
    <%= f.text_field :foto_juez %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jueces/edit.html.erb
<h1>Editing juece</h1>

<%= render 'form' %>

<%= link_to 'Show', @juece %> |
<%= link_to 'Back', jueces_path %>

app/views/jueces/index.html.erb
<h1>Listing jueces</h1>

<table>
  <thead>
    <tr>
      <th>Nombre juez</th>
      <th>Apellido pat juez</th>
      <th>Apellido mat juez</th>
      <th>Rut juez</th>
      <th>Sexo juez</th>
      <th>Fecha nac juez</th>
      <th>Email juez</th>
      <th>Foto juez</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jueces.each do |juece| %>
      <tr>
        <td><%= juece.nombre_juez %></td>
        <td><%= juece.apellido_pat_juez %></td>
        <td><%= juece.apellido_mat_juez %></td>
        <td><%= juece.rut_juez %></td>
        <td><%= juece.sexo_juez %></td>
        <td><%= juece.fecha_nac_juez %></td>
        <td><%= juece.email_juez %></td>
        <td><%= juece.foto_juez %></td>
        <td><%= link_to 'Show', juece %></td>
        <td><%= link_to 'Edit', edit_juece_path(juece) %></td>
        <td><%= link_to 'Destroy', juece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Juece', new_juece_path %>

app/views/jueces/new.html.erb
<h1>New juece</h1>

<%= render 'form' %>

<%= link_to 'Back', jueces_path %>

app/views/jueces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre juez:</strong>
  <%= @juece.nombre_juez %>
</p>

<p>
  <strong>Apellido pat juez:</strong>
  <%= @juece.apellido_pat_juez %>
</p>

<p>
  <strong>Apellido mat juez:</strong>
  <%= @juece.apellido_mat_juez %>
</p>

<p>
  <strong>Rut juez:</strong>
  <%= @juece.rut_juez %>
</p>

<p>
  <strong>Sexo juez:</strong>
  <%= @juece.sexo_juez %>
</p>

<p>
  <strong>Fecha nac juez:</strong>
  <%= @juece.fecha_nac_juez %>
</p>

<p>
  <strong>Email juez:</strong>
  <%= @juece.email_juez %>
</p>

<p>
  <strong>Foto juez:</strong>
  <%= @juece.foto_juez %>
</p>

<%= link_to 'Edit', edit_juece_path(@juece) %> |
<%= link_to 'Back', jueces_path %>