config/routes.rb
Rails.application.routes.draw do
  resources :rol_jueces

  resources :jueces

  resources :equipos

  resources :participante_competencia

  resources :rol_tecnicos

  resources :tecnicos

  resources :jugadors

  resources :encuentros

  resources :recintos

  resources :organizadors

  get 'nueva_competencia/paso1'
  post 'nueva_competencia/paso1'

  get 'nueva_competencia/paso2'
  post 'nueva_competencia/paso2'

  get 'nueva_competencia/paso3'
  post 'nueva_competencia/paso3'

  get 'nueva_competencia/paso4'
  post 'nueva_competencia/paso4'

  get 'nueva_competencia/paso5'
  post 'nueva_competencia/paso5'

  get 'nueva_competencia/paso6'
  post 'nueva_competencia/paso6'

  get 'nueva_competencia/paso7'
  post 'nueva_competencia/paso7'

  get 'nueva_competencia/paso8'
  post 'nueva_competencia/paso8'

  get 'nueva_competencia/paso9'
  post 'nueva_competencia/paso9'

  get 'home/index'

  root :to => 'home#index'
  devise_for :users

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.administrador?
         can :manage, :all
       elsif user.organizador?
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/competencia.rb
class Competencia < ActiveRecord::Base
	
end

app/models/convocatoria.rb
class Convocatoria < ActiveRecord::Base
  belongs_to :jugador
  belongs_to :participante
end

app/models/encuentro.rb
class Encuentro < ActiveRecord::Base
end

app/models/equipo.rb
class Equipo < ActiveRecord::Base
  belongs_to :encuentro
  belongs_to :convocatoria
end

app/models/etapa.rb
class Etapa < ActiveRecord::Base
  belongs_to :competencia
  belongs_to :etapa
end

app/models/juece.rb
class Juece < ActiveRecord::Base
end

app/models/jugador.rb
class Jugador < ActiveRecord::Base
end

app/models/organizador.rb
class Organizador < ActiveRecord::Base
	has_many :Competencia
end

app/models/participante.rb
class Participante < ActiveRecord::Base
end

app/models/recinto.rb
class Recinto < ActiveRecord::Base
end

app/models/rol_cuerpo_tecnico.rb
class RolCuerpoTecnico < ActiveRecord::Base
  belongs_to :rol_tecnico
  belongs_to :participante_competencium
end

app/models/rol_juece.rb
class RolJuece < ActiveRecord::Base
end

app/models/rol_tecnico.rb
class RolTecnico < ActiveRecord::Base
end

app/models/tecnico.rb
class Tecnico < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
  ROLES = %i[administrador organizador juez entrenador jugador]
   
  def roles=(roles)
    roles = [*roles].map { |r| r.to_sym }
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end
  def has_role?(role)
    roles.include?(role)
  end
  
# in models/user.rb
  def is?(role)
    roles.include?(role.to_s)
  end
end

app/controllers/tecnicos_controller.rb
class TecnicosController < ApplicationController
  before_action :set_tecnico, only: [:show, :edit, :update, :destroy]

  # GET /tecnicos
  # GET /tecnicos.json
  def index
    @tecnicos = Tecnico.all
  end

  # GET /tecnicos/1
  # GET /tecnicos/1.json
  def show
  end

  # GET /tecnicos/new
  def new
    @tecnico = Tecnico.new
  end

  # GET /tecnicos/1/edit
  def edit
  end

  # POST /tecnicos
  # POST /tecnicos.json
  def create
    @tecnico = Tecnico.new(tecnico_params)

    respond_to do |format|
      if @tecnico.save
        format.html { redirect_to @tecnico, notice: 'Tecnico was successfully created.' }
        format.json { render :show, status: :created, location: @tecnico }
      else
        format.html { render :new }
        format.json { render json: @tecnico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tecnicos/1
  # PATCH/PUT /tecnicos/1.json
  def update
    respond_to do |format|
      if @tecnico.update(tecnico_params)
        format.html { redirect_to @tecnico, notice: 'Tecnico was successfully updated.' }
        format.json { render :show, status: :ok, location: @tecnico }
      else
        format.html { render :edit }
        format.json { render json: @tecnico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tecnicos/1
  # DELETE /tecnicos/1.json
  def destroy
    @tecnico.destroy
    respond_to do |format|
      format.html { redirect_to tecnicos_url, notice: 'Tecnico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tecnico
      @tecnico = Tecnico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tecnico_params
      params.require(:tecnico).permit(:nombre_tec, :apellido_pat_tec, :apellido_mat_tec, :rut_tec, :sexo_tec, :fecha_nac_tec, :email_tec, :foto_tec)
    end
end

app/helpers/encuentros_helper.rb
module EncuentrosHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jugadors_helper.rb
module JugadorsHelper
end

app/helpers/recintos_helper.rb
module RecintosHelper
end

app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

app/views/tecnicos/_form.html.erb
<%= form_for(@tecnico) do |f| %>
  <% if @tecnico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tecnico.errors.count, "error") %> prohibited this tecnico from being saved:</h2>

      <ul>
      <% @tecnico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_tec %><br>
    <%= f.text_field :nombre_tec %>
  </div>
  <div class="field">
    <%= f.label :apellido_pat_tec %><br>
    <%= f.text_field :apellido_pat_tec %>
  </div>
  <div class="field">
    <%= f.label :apellido_mat_tec %><br>
    <%= f.text_field :apellido_mat_tec %>
  </div>
  <div class="field">
    <%= f.label :rut_tec %><br>
    <%= f.text_field :rut_tec %>
  </div>
  <div class="field">
    <%= f.label :sexo_tec %><br>
    <%= f.check_box :sexo_tec %>
  </div>
  <div class="field">
    <%= f.label :fecha_nac_tec %><br>
    <%= f.date_select :fecha_nac_tec %>
  </div>
  <div class="field">
    <%= f.label :email_tec %><br>
    <%= f.text_field :email_tec %>
  </div>
  <div class="field">
    <%= f.label :foto_tec %><br>
    <%= f.text_field :foto_tec %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tecnicos/edit.html.erb
<h1>Editing tecnico</h1>

<%= render 'form' %>

<%= link_to 'Show', @tecnico %> |
<%= link_to 'Back', tecnicos_path %>

app/views/tecnicos/index.html.erb
<h1>Listing tecnicos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre tec</th>
      <th>Apellido pat tec</th>
      <th>Apellido mat tec</th>
      <th>Rut tec</th>
      <th>Sexo tec</th>
      <th>Fecha nac tec</th>
      <th>Email tec</th>
      <th>Foto tec</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tecnicos.each do |tecnico| %>
      <tr>
        <td><%= tecnico.nombre_tec %></td>
        <td><%= tecnico.apellido_pat_tec %></td>
        <td><%= tecnico.apellido_mat_tec %></td>
        <td><%= tecnico.rut_tec %></td>
        <td><%= tecnico.sexo_tec %></td>
        <td><%= tecnico.fecha_nac_tec %></td>
        <td><%= tecnico.email_tec %></td>
        <td><%= tecnico.foto_tec %></td>
        <td><%= link_to 'Show', tecnico %></td>
        <td><%= link_to 'Edit', edit_tecnico_path(tecnico) %></td>
        <td><%= link_to 'Destroy', tecnico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tecnico', new_tecnico_path %>

app/views/tecnicos/new.html.erb
<h1>New tecnico</h1>

<%= render 'form' %>

<%= link_to 'Back', tecnicos_path %>

app/views/tecnicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre tec:</strong>
  <%= @tecnico.nombre_tec %>
</p>

<p>
  <strong>Apellido pat tec:</strong>
  <%= @tecnico.apellido_pat_tec %>
</p>

<p>
  <strong>Apellido mat tec:</strong>
  <%= @tecnico.apellido_mat_tec %>
</p>

<p>
  <strong>Rut tec:</strong>
  <%= @tecnico.rut_tec %>
</p>

<p>
  <strong>Sexo tec:</strong>
  <%= @tecnico.sexo_tec %>
</p>

<p>
  <strong>Fecha nac tec:</strong>
  <%= @tecnico.fecha_nac_tec %>
</p>

<p>
  <strong>Email tec:</strong>
  <%= @tecnico.email_tec %>
</p>

<p>
  <strong>Foto tec:</strong>
  <%= @tecnico.foto_tec %>
</p>

<%= link_to 'Edit', edit_tecnico_path(@tecnico) %> |
<%= link_to 'Back', tecnicos_path %>